Parenthesis implementation
biancaguzenski/pibs-lang pull request #5
Opened 2020-07-23 17:04 UTC by biancaguzenski

O objetivo era  implementar parênteses na classe evaluator. O caminho que escolhi foi criar uma nova função que verificaria presença de parênteses toda vez que o primeiro nível fosse chamado. Caso não houvesse parênteses, seria devolvido o valor atual do token.
À exceção dos testes para avaliar expressão iniciada por operador, todos passaram.

2020-07-27 13:32 UTC, pmargreff requested changes
Deixei alguns comentários no sentido de melhorar a legibilidade e o reuso de código. No geral acho que tá no caminho certo! 👍🏽

2020-07-27 13:32 UTC, pmargreff commented on evaluator.rb
> +  def is_parenthesis()
Normalmente no ruby, o prefixo `is_...` é usado [como convenção para métodos que retornam um bool](https://github.com/rubocop-hq/ruby-style-guide#predicate-methods-prefix), o que não é o caso. 

Qual nome pode ser usado para melhorar aqui? Dica: você pode usar o metódo público dessa classe como referência.

2020-07-27 13:32 UTC, pmargreff commented on evaluator.rb
> +    elsif token.sum?
Acho que isso pode ser escrito melhor. Você duplicou uma lógica que já existe em uma outra função, não consegue usar esse função ao invés de reescrever ela aqui?

2020-07-27 13:32 UTC, pmargreff commented on evaluator.rb
> +    elsif (token.mult? || token.div?)
Você consegue escrever um teste pra esse caso de erro?

2020-07-27 13:32 UTC, pmargreff commented on spec/evaluator_spec.rb
> +    it "evaluates omplex operation with more than one parenthesis" do
Tanto nesse caso, quanto nos anteriores, está bastente ruim de ler o que está sendo testado. Você pode (deve?) colocar a expressão junto á descrição do teste?

2020-07-27 13:32 UTC, pmargreff commented on spec/execute_program.rb
> +interpreter = Interpreter.new("spec/multiple_expressions.pibs")
❤️

2020-07-27 18:18 UTC, biancaguzenski commented on evaluator.rb
> +    elsif token.sum?
Nessa porção de código que tu marcou não encontrei duplicata de código. Seria nas linhas seguintes, onde posso trocar o (token.mult? || token.div?) por operation_mult_or_div?() ?

2020-07-27 18:19 UTC, biancaguzenski commented on evaluator.rb
> +    elsif (token.mult? || token.div?)
Escrevi testes para -1, 0-1, (-1) e todos passaram, é suficiente?

2020-07-27 18:25 UTC, pmargreff commented on evaluator.rb
> +    elsif token.sum?
[Aqui!](https://github.com/biancaguzenski/pibs-lang/pull/5/files#diff-ecdb9127fd78d851e391638907bfb29dL33)

2020-07-27 18:26 UTC, pmargreff commented on evaluator.rb
> +    elsif (token.mult? || token.div?)
Não, qual caso de teste testa os cenários onde a linha 72 é executada? Como você tem certeza que ela é executada?

2020-07-28 11:34 UTC, biancaguzenski commented on evaluator.rb
> +    elsif (token.mult? || token.div?)
Sim, fiz os testes da linha 79 e 105 para verificar esses casos.

2020-07-28 11:40 UTC, pmargreff commented on evaluator.rb
> +      return 0
Isso aqui me parece errado, por que temos uma operação diferente pra soma e subtração?

2020-07-28 12:19 UTC, 3ianc4 reviewed
@pmargreff Fiz todas as modificações requisitadas. A descrição dos testes eu não tenho certeza se é suficiente, mas achei bem mais claro.

2020-07-28 12:19 UTC, 3ianc4 commented on spec/evaluator_spec.rb
> +    it "evaluates times operator in first position" do
Aqui @pmargreff

2020-07-28 12:19 UTC, 3ianc4 commented on spec/evaluator_spec.rb
> +
Aqui @pmargreff

2020-07-28 12:19 UTC, biancaguzenski commented on evaluator.rb
> +      return 0
Corrigido.

2020-07-28 19:56 UTC, merged